### ISSUE TITLE
Code Refactor 

### ISSUE THREAD

**Issue by charan2308** [acmpesuecc/was_a_game#1]
As you can observe the code is messed up. Please clean the code up for better readability and maintainability :)

**Comment by pushkar-gr** [comment]
Yo can I ?

**Comment by rojasbinny-yb** [comment]
Can I be assigned to this?

**Comment by Sanjaya2204** [comment]
May I?

**Comment by nive404** [comment]
can i be assigned to this issue

**Comment by Archit-Rode** [comment]
Can i be assigned please

**Comment by anshiiJ** [comment]
pls assign this issue to me

**Comment by Mrigank-J** [comment]
may i take this?

**Comment by Sarah-Alex** [comment]
pliss assign

**Comment by ManushriJ** [comment]
can i get assigned

**Comment by RisuKumari11** [comment]
can I get this issue

**Comment by Advaith2805** [comment]
Can i get assigned

**Comment by 7Akshu77** [comment]
can I get  this issue assigned

**Comment by siribins** [comment]
can i be assigned this issue

**Comment by SuchitraShankar07** [comment]
could i pls be assigned to this issue

**Comment by nikita-s-nair** [comment]
could i get assigned to this issue?

**Comment by euphoricair7** [comment]
Could You assign me this issue?

**Comment by 1anagha7** [comment]
please assign me this issue

**Comment by neethanm** [comment]
can i be assigned to this?
