### ISSUE TITLE
fix the feedback for the game

### ISSUE THREAD

**Issue by charan2308** [acmpesuecc/was_a_game#2]
I messed while changing the structure of the project . 
Now the feed back is not getting saved in feedback.txt fix the path.

**Comment by Nightwing000** [comment]
can i be assigned this issue

**Comment by shakirth-anisha** [comment]
can this be assigned to me??

**Comment by Drakonxd786** [comment]
can this be assigned to me ??

**Comment by Suhaniverma2004** [comment]
can i get assigned?

**Comment by HemaShree0408** [comment]
can i get assigned?

**Comment by RishavSinha20** [comment]
please assign me

**Comment by icantype1912** [comment]
Assign this to me please i will work on thiss and hopefully have a fix(hopefully)

**Comment by NJWasTaken** [comment]
Can I be assigned?

**Comment by LalithaTanmayee** [comment]
Can this be assigned to me?

**Comment by ankitkumar099** [comment]
can u assign me

**Comment by HackerGlory** [comment]
please assign this to me

**Comment by pushkar-gr** [comment]
can I be assigned ?

**Comment by ankitkumar099** [comment]
can i be assign immediatly??

**Comment by ghost** [comment]
can i be assigned ASAP

**Comment by Nightwing000** [comment]
Can i be assigned this issue

**Comment by 411sst** [comment]
can i get assigned if this is still open?

**Comment by UdayaPragna** [comment]
could you please assingn me to this issue

**Comment by ShaheedMirjanaik** [comment]
@charan2308  could you please assingn me to this issue

**Comment by charan2308** [comment]
@ShaheedMirjanaik go ahead with it

**Comment by charan2308** [comment]
if anybody wants to work on this , you can request now

**Comment by Drakonxd786** [comment]
can this be assigned to me?

**Comment by charan2308** [comment]
@Drakonxd786 go ahead
