### ISSUE TITLE
Implement autoscroll on the story textarea

### ISSUE THREAD

**Issue by charan2308** [acmpesuecc/was_a_game#3]
On the GUI, there is a textarea(scrolledtext) on which the storyline is printed as the story progresses. Once the available textarea is filled, it keeps appending the next storyline on the textarea, which cannot be seen directly . After this, the user has to scroll down to see the recently added storyline.
The text area doesn't scroll when the game is proceeding
Please implement an autoscroll feature, where, once the textarea is filled, it automatically scrolls to the recently inserted storyline.

**Comment by Rhn14** [comment]
assign me this issue

**Comment by Nightwing000** [comment]
can i be assigned this issue

**Comment by akdino** [comment]
can i get assigned?

**Comment by kavs2803** [comment]
can i be assigned ?

**Comment by Drakonxd786** [comment]
can this be assigned to me ?

**Comment by uditreddys** [comment]
can you assign this 

i am working on this

**Comment by Advaith2805** [comment]
Can i be assigned

**Comment by siri-n-shetty** [comment]
Can I get assigned, please???

**Comment by Nightwing000** [comment]
![image](https://github.com/acmpesuecc/was_a_game/assets/98019602/28928674-a9a1-49e1-baa4-f9ca7968b159)
so i ran into an SSH key issue(fixed now) can i have more time for this issue

**Comment by Keeru-2005** [comment]
can u pls assign this to me?
i will work on this
