### ISSUE TITLE
better ending of the game or the end part of the game

### ISSUE THREAD

**Issue by charan2308** [acmpesuecc/was_a_game#4]
I ran out of time while making this project and the last stage of the game is somewhat messy. Get creative and give the game the closure it deserves :)

**Comment by Rhn14** [comment]
assign me this issue

**Comment by Nightwing000** [comment]
can i be assigned this issue

**Comment by nive404** [comment]
can i be assigned to this issue

**Comment by sxijyoti** [comment]
can i be assigned this?

**Comment by nik2203** [comment]
Could I be assigned this issue?

**Comment by DedLad** [comment]
can i have this?

**Comment by charan2308** [comment]
go ahead with it @Rhn14

**Comment by ShankyTaco** [comment]
Assign me this issue

**Comment by icantype1912** [comment]
assign me this issue pls

**Comment by Manvith-M-Nayak** [comment]
can you assign me this?

**Comment by NJWasTaken** [comment]
Can I be assigned?

**Comment by SuchitraShankar07** [comment]
Could i please be assigned this

**Comment by Hiyanachnani** [comment]
hii could you please assign this issue to me

**Comment by N0Xl0US** [comment]
asign me this, thank you

**Comment by samarth777** [comment]
can you assign me to this

**Comment by 7Akshu77** [comment]
can I get assigned to this issue

**Comment by NJWasTaken** [comment]
Can I be assigned?

**Comment by Lalith2907** [comment]
can you please assign me to this

**Comment by 411sst** [comment]
can i get assigned if this is still open?
